### ISSUE TITLE
Isn't these too many authorities to display flag for a address?

### ISSUE THREAD

**Issue by paulvi** [andy-portmen/country-flags#65]
Isn't these too many authorities to display flag for a address?

![image](https://user-images.githubusercontent.com/1614482/67536139-47eca180-f708-11e9-92f9-1ca4dc317e75.png)

Could you please list those are needed.

**Comment by andy-portmen** [comment]
These are all needed. See https://add0n.com/country-flags.html#permissions for more info.

However, it turned out that I can move some of these permissions into the optional section so that the permission is only granted if the user needs the feature.

old:
![old](https://user-images.githubusercontent.com/6779535/67631509-53b6a000-f88f-11e9-9a84-b0b4b29a4527.png)
upcoming:
![upcoming](https://user-images.githubusercontent.com/6779535/67631512-67620680-f88f-11e9-96d1-aa8c7be7f351.png)

Based on https://github.com/andy-portmen/country-flags/commit/aede01cbbaa603007b3cfce4d10c8cfbb5ce19cf

**Comment by paulvi** [comment]
Thank you for clarification.

Yes, it would be nice, when Permissions are requested when extra feature is used first time.
