### ISSUE TITLE
Unable to log in to cloudflare.com

### ISSUE THREAD

**Issue by shuohua2000** [andy-portmen/country-flags#70]
Problem description: Unable to log in to cloudflare.com
Details: I have been using "Country Flags & IP Whois" all the time, it works very well, but yesterday I was unable to log in to my cloudflare account, "https://dash.cloudflare.com/", always prompted "Please refresh the page.". I tried to disable the extensions one by one, and finally found that as long as "Country Flags & IP Whois" is enabled, you will not be able to log in. After the disablement, the problem is solved.
Chrome version: 83.0.4103.106
Chrome console error code: POST https://dash.cloudflare.com/login 401

**Comment by andy-portmen** [comment]
I tried the add-on and I can open "https://dash.cloudflare.com/login" with no problem (haven't tried to actually login though). The "Country Flags" add-on does not inject any script into any website and has no server interruption, so I still don't see how a website can detect the add-on presence. Have you tried on a clean profile just with this add-on installed instead of disabling one by one? Is this on FF or Chrome?

**Comment by shuohua2000** [comment]
thank you for your reply!
"https://dash.cloudflare.com/login" can be opened normally, just click "Login" button and it will prompt "Please refresh the page." Chrome version: 83.0.4103.106. I also tried Chromium-based EDGE The browser is also unable to log in, version: 83.0.478.54
I also tried to use Firefox, version: 77.0.1, everything works fine.
The above three browsers have installed the latest version of "Country Flags & IP Whois".
Any suggestions are greatly appreciated!

**Comment by andy-portmen** [comment]
This is fixed on the new release. Thanks for the report.
https://github.com/andy-portmen/country-flags/commit/5b0048c757a5f01c38606231a8fe8b0d2239dc68
